default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost


development:
  <<: *default
  database: curate-it-api_development

test:
  <<: *default
  database: curate-it-api_test
