default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: curate-it-api_development

test:
  <<: *default
  database: curate-it-api_test

production:
  <<: *default
  database: curate-it-api_production
